name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "104.19.139.136:443,129.154.59.54:443,152.67.203.34:443,www.visakorea.com,www.visa.co.jp,www.visa.com.sg"
UUID = "1b6c1745-992e-4aac-8685-266c090e50ea"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
